---
development:
  cloud_name: webdev09
  api_key: '764393886628717'
  api_secret: X6hCtRxcaAVqpoEWA7bUiDt4iZY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: webdev09
  api_key: '764393886628717'
  api_secret: X6hCtRxcaAVqpoEWA7bUiDt4iZY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: webdev09
  api_key: '764393886628717'
  api_secret: X6hCtRxcaAVqpoEWA7bUiDt4iZY
  enhance_image_tag: true
  static_image_support: false
